### ISSUE TITLE
Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by DipFlip** [deepaksamuel/simple#1]
Hi! 
First of all - this program looks great and I'm very excited to try it. I tested the Ubuntu 16.04 version from [here](https://github.com/deepaksamuel/simple/releases/download/v0.8-alpha/simple-ubuntu-16.04-x64-allfiles.zip) on Ubuntu 18.04 so probably that is why but maybe you can see if I'm doing something else wrong.

I've downloaded GEANT4 datasets and set the paths so the program can find them all and when I try to launch it without checking the "First time use" checkbox I get the error below.

`emil@emil-XPS13:~/myinstalls/simple_G4$ ./Simple-Ubuntu-16.04-x86_64.AppImage 
QMetaObject::connectSlotsByName: No matching signal for on_duplicate_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_delete_object_clicked()
Output directory set to:  "/home/emil/myinstalls/simple_G4/output/"
"UPDATE env_vars SET value='/home/emil/myinstalls/simple_G4/output/' WHERE env_var='OUTPUTDIR'"
QMetaObject::connectSlotsByName: No matching signal for on_show_recent_files_clicked(bool)
QMetaObject::connectSlotsByName: No matching signal for on_show_recent_files_clicked()
Could not find file in recent list:  "/home/samuel/simple/simple/models/bragg-peak.sim"
Could not find file in recent list:  "/home/samuel/simple/simple/models/cobalt-decay.sim"
Could not find file in recent list:  "/home/samuel/simple/simple/models/mICAL.sim"
Could not find file in recent list:  "/home/samuel/simple/simple/models/ICAL2.sim"
Could not find file in recent list:  "/home/samuel/simple/simple/deploy-tools/models/gold-foil.sim"
Could not find file in recent list:  "/home/samuel/fnal/DUNE_ND_sim/geometry/MPD_SPY_LAr.gdml"
Could not find file in recent list:  "/home/samuel/fnal/DUNE_ND_sim/geometry/MPD_SPY_wMuID.gdml"
Could not find file in recent list:  "/home/samuel/simple/simple/deploy-tools/models/mICAL.sim"`

Then I click the "Ok" box to start and get:

`G4PhysListFactory::GetReferencePhysList <FTFP_BERT>  EMoption= 0

-------- EEEE ------- G4Exception-START -------- EEEE -------

*** ExceptionHandler is not defined ***
*** G4Exception : PART70001
      issued by : G4NuclideTable
ENSDFSTATE.dat is not found.
*** Fatal Exception ***
-------- EEEE ------- G4Exception-END -------- EEEE -------

*** G4Exception: Aborting execution ***
Aborted (core dumped)`

I'll try setting up a 19.10 environment to test but thought it could be useful perhaps to share this!
Keep up the great work :) 
Cheers!

**Comment by deepaksamuel** [comment]
Hi,
Thanks for your encouragement. The error is because Simple could not locate the datasets. It searches for them in the local environment variables that can be set in the 'First time use' of Simple. I would suggest that you click the 'First time use' and you will see a table where the path to the datasets can be set. The easiest way to set these is by clicking the 'Auto search' button (beneath the table) and in the dialog box that pops up, select the folder that contains all these datasets. Once this is done, click 'Update'. If the datasets are not found, an error message is displayed. The details of the error can be seen in the Messages tab (lower left).

You must restart Simple after these steps and then you need not check the 'First time use' option the next time. 

Please let me know if this helped.

Deepak Samuel

**Comment by DipFlip** [comment]
Thanks for getting back. I did set the folders like that before and still get the output I pasted above. If I check "First time use" again the GUI till show up and I will see the paths I've set earlier. Clicking "Update" doesn't show any errors so I think the paths are found, right? Here's a screenshot:
![image](https://user-images.githubusercontent.com/12473575/85225023-85f0b100-b3ce-11ea-85ba-ef93538f26e0.png)

**Comment by DipFlip** [comment]
Ah the "Auto search" did the trick as you suggested. When I unpacked the GEANT4 datasets they went into a folder structure like this g4_data/G4PII.1.3/G4PII1.3/ and my mistake was setting them to only g4_data/G4PII.1.3/
Thanks again for the help!

![image](https://user-images.githubusercontent.com/12473575/85225457-c00f8200-b3d1-11ea-90d9-499e63e0e955.png)
